### ISSUE TITLE
Add option to only move if only one monitor is detected

### ISSUE THREAD

**Issue by PapierFliegr** [Ubiquitine/MACsimize6#11]
When using multiple monitors, it's somehow a hassel that everytime I maximize a window it gets moved to a new virtual desktop.

Could you add the option to only enable the script if one desktop is being detected?
I think relevant functions here are `workspace.screens` and `screenAdded()`, `screenRemoved()`

**Comment by Ubiquitine** [comment]
Could you try to use [Virtual-desktops-only-on-primary](https://github.com/Ubiquitine/virtual-desktops-only-on-primary) for multiple monitors? 
You suggestion is valid. When I have time I'll work on this. Also PRs are welcome if you know hot to implement it already.
