### ISSUE TITLE
Changing Settings requires relogin

### ISSUE THREAD

**Issue by PapierFliegr** [Ubiquitine/MACsimize6#14]
Checking/Unchecking an option requires relogin.
The script doesn't update readable Configs.
Not sure if that is intended behavior (I tried to fix it, but wasn't able to).

**Comment by Ubiquitine** [comment]
I think that there is no way to force KWin scripts to re-read their config when you update it. At least, not in the way how this script is implemented. I saw script like Polonium that don't need script to be restarted to apply changes, but they use a completely different approach and way more complex.   
But you don't need to relogin. You can just disable the script, then enable it again (clicking the "apply" button in between).
This, however, would make the script to forget about saved state of the windows and their virtual desktops, but it is a bit better than logging out.
