### ISSUE TITLE
Add "ksplash" and "ksplashqml" as default exclusion

### ISSUE THREAD

**Issue by yoelwep13578** [Ubiquitine/MACsimize6#7]
After logging in from SDDM, the Splash Screen usually appears with the default Plasma logo and the text "Made by KDE." The problem is, when the Kwin Script MACsimize is run, the Splash Screen also "Creates a new Desktop" and leaves a "Desktop" trace after the Splash Screen disappears.
![image](https://github.com/user-attachments/assets/62b73470-16ec-4574-b6b9-62ce02ae9e71)

This issue aims to be the next enhancement to add "ksplash" and "ksplashqml" to the Exception List by default.

**Comment by Ubiquitine** [comment]
Thank you for you report.
Did you test this, by adding these two classes to the script configuration Ignore list?
Both default/built-in and user defined Ignore lists are merged, so adding classes in either produce the same result.
Please confirm that adding these classes to Ignore list fixes the issue, and I'll include them in the default list in the next version.

**Comment by yoelwep13578** [comment]
Thanks for your response.

I can confirm that this works as I have tested it. When `ksplash` and `ksplashqml` are added, the issue is resolved after logging in from SDDM (no more "desktop" trace left behind)

![image](https://github.com/user-attachments/assets/b0b80d1c-3dea-45f7-be00-95fdb119b926)

I forgot to add this yesterday; sorry for the confusion caused before.

.

**[Before adding ksplash and ksplashqml]**

1. Login from SDDM
2. Suddenly, the splash screen slides to "New Desktop"
3. After the splash screen disappears, the "New Desktop" trace remains and has to be removed manually.

**[After adding ksplash and ksplashqml]**

1. Login from SDDM
2. The splash screen displays perfectly, no sliding as before
3. After the splash screen disappears, there is no "New Desktop" trace left.
